// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: pkg/protobufs/catalog/catalog.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []string               `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPricesRequest) Reset() {
	*x = CheckPricesRequest{}
	mi := &file_pkg_protobufs_catalog_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPricesRequest) ProtoMessage() {}

func (x *CheckPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobufs_catalog_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPricesRequest.ProtoReflect.Descriptor instead.
func (*CheckPricesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobufs_catalog_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPricesRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type ProductCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,3,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCheck) Reset() {
	*x = ProductCheck{}
	mi := &file_pkg_protobufs_catalog_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCheck) ProtoMessage() {}

func (x *ProductCheck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobufs_catalog_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCheck.ProtoReflect.Descriptor instead.
func (*ProductCheck) Descriptor() ([]byte, []int) {
	return file_pkg_protobufs_catalog_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ProductCheck) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductCheck) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductCheck) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type CheckPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductCheck        `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPricesResponse) Reset() {
	*x = CheckPricesResponse{}
	mi := &file_pkg_protobufs_catalog_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPricesResponse) ProtoMessage() {}

func (x *CheckPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobufs_catalog_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPricesResponse.ProtoReflect.Descriptor instead.
func (*CheckPricesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobufs_catalog_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *CheckPricesResponse) GetProducts() []*ProductCheck {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_pkg_protobufs_catalog_catalog_proto protoreflect.FileDescriptor

const file_pkg_protobufs_catalog_catalog_proto_rawDesc = "" +
	"\n" +
	"#pkg/protobufs/catalog/catalog.proto\x12\acatalog\"5\n" +
	"\x12CheckPricesRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\tR\n" +
	"productIds\"f\n" +
	"\fProductCheck\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12!\n" +
	"\fis_available\x18\x03 \x01(\bR\visAvailable\"H\n" +
	"\x13CheckPricesResponse\x121\n" +
	"\bproducts\x18\x01 \x03(\v2\x15.catalog.ProductCheckR\bproducts2\\\n" +
	"\x0eCatalogService\x12J\n" +
	"\vCheckPrices\x12\x1b.catalog.CheckPricesRequest\x1a\x1c.catalog.CheckPricesResponse\"\x00B!Z\x1fecommerce/pkg/protobufs/catalogb\x06proto3"

var (
	file_pkg_protobufs_catalog_catalog_proto_rawDescOnce sync.Once
	file_pkg_protobufs_catalog_catalog_proto_rawDescData []byte
)

func file_pkg_protobufs_catalog_catalog_proto_rawDescGZIP() []byte {
	file_pkg_protobufs_catalog_catalog_proto_rawDescOnce.Do(func() {
		file_pkg_protobufs_catalog_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protobufs_catalog_catalog_proto_rawDesc), len(file_pkg_protobufs_catalog_catalog_proto_rawDesc)))
	})
	return file_pkg_protobufs_catalog_catalog_proto_rawDescData
}

var file_pkg_protobufs_catalog_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_protobufs_catalog_catalog_proto_goTypes = []any{
	(*CheckPricesRequest)(nil),  // 0: catalog.CheckPricesRequest
	(*ProductCheck)(nil),        // 1: catalog.ProductCheck
	(*CheckPricesResponse)(nil), // 2: catalog.CheckPricesResponse
}
var file_pkg_protobufs_catalog_catalog_proto_depIdxs = []int32{
	1, // 0: catalog.CheckPricesResponse.products:type_name -> catalog.ProductCheck
	0, // 1: catalog.CatalogService.CheckPrices:input_type -> catalog.CheckPricesRequest
	2, // 2: catalog.CatalogService.CheckPrices:output_type -> catalog.CheckPricesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_protobufs_catalog_catalog_proto_init() }
func file_pkg_protobufs_catalog_catalog_proto_init() {
	if File_pkg_protobufs_catalog_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protobufs_catalog_catalog_proto_rawDesc), len(file_pkg_protobufs_catalog_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protobufs_catalog_catalog_proto_goTypes,
		DependencyIndexes: file_pkg_protobufs_catalog_catalog_proto_depIdxs,
		MessageInfos:      file_pkg_protobufs_catalog_catalog_proto_msgTypes,
	}.Build()
	File_pkg_protobufs_catalog_catalog_proto = out.File
	file_pkg_protobufs_catalog_catalog_proto_goTypes = nil
	file_pkg_protobufs_catalog_catalog_proto_depIdxs = nil
}
