// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: pkg/protobufs/payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_pkg_protobufs_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobufs_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobufs_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentUrl    string                 `protobuf:"bytes,1,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_pkg_protobufs_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobufs_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobufs_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *CreatePaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

var File_pkg_protobufs_payment_payment_proto protoreflect.FileDescriptor

const file_pkg_protobufs_payment_payment_proto_rawDesc = "" +
	"\n" +
	"#pkg/protobufs/payment/payment.proto\x12\apayment\"~\n" +
	"\x14CreatePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"_\n" +
	"\x15CreatePaymentResponse\x12\x1f\n" +
	"\vpayment_url\x18\x01 \x01(\tR\n" +
	"paymentUrl\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId2g\n" +
	"\x0ePaymentService\x12U\n" +
	"\x14CreatePaymentSession\x12\x1d.payment.CreatePaymentRequest\x1a\x1e.payment.CreatePaymentResponseB!Z\x1fecommerce/pkg/protobufs/paymentb\x06proto3"

var (
	file_pkg_protobufs_payment_payment_proto_rawDescOnce sync.Once
	file_pkg_protobufs_payment_payment_proto_rawDescData []byte
)

func file_pkg_protobufs_payment_payment_proto_rawDescGZIP() []byte {
	file_pkg_protobufs_payment_payment_proto_rawDescOnce.Do(func() {
		file_pkg_protobufs_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protobufs_payment_payment_proto_rawDesc), len(file_pkg_protobufs_payment_payment_proto_rawDesc)))
	})
	return file_pkg_protobufs_payment_payment_proto_rawDescData
}

var file_pkg_protobufs_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protobufs_payment_payment_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),  // 0: payment.CreatePaymentRequest
	(*CreatePaymentResponse)(nil), // 1: payment.CreatePaymentResponse
}
var file_pkg_protobufs_payment_payment_proto_depIdxs = []int32{
	0, // 0: payment.PaymentService.CreatePaymentSession:input_type -> payment.CreatePaymentRequest
	1, // 1: payment.PaymentService.CreatePaymentSession:output_type -> payment.CreatePaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protobufs_payment_payment_proto_init() }
func file_pkg_protobufs_payment_payment_proto_init() {
	if File_pkg_protobufs_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protobufs_payment_payment_proto_rawDesc), len(file_pkg_protobufs_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protobufs_payment_payment_proto_goTypes,
		DependencyIndexes: file_pkg_protobufs_payment_payment_proto_depIdxs,
		MessageInfos:      file_pkg_protobufs_payment_payment_proto_msgTypes,
	}.Build()
	File_pkg_protobufs_payment_payment_proto = out.File
	file_pkg_protobufs_payment_payment_proto_goTypes = nil
	file_pkg_protobufs_payment_payment_proto_depIdxs = nil
}
